// Auto-Generated by FAKE; do not edit
namespace Fsion
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fsion")>]
[<assembly: AssemblyProductAttribute("Fsion")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018")>]
[<assembly: AssemblyDescriptionAttribute("EAVT (Entity Attribute Value Time) database for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.8")>]
[<assembly: AssemblyFileVersionAttribute("0.0.8")>]
[<assembly: InternalsVisibleToAttribute("Fsion.Tests")>]
[<assembly: InternalsVisibleToAttribute("Fsion.Excel")>]
do ()

