// Auto-Generated by FAKE; do not edit
namespace Fsion
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fsion")>]
[<assembly: AssemblyProductAttribute("Fsion")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018")>]
[<assembly: AssemblyDescriptionAttribute("EAVT (Entity Attribute Value Time) database for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.7")>]
[<assembly: AssemblyFileVersionAttribute("0.0.7")>]
[<assembly: InternalsVisibleToAttribute("Fsion.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fsion"
    let [<Literal>] AssemblyProduct = "Fsion"
    let [<Literal>] AssemblyCopyright = "Copyright 2018"
    let [<Literal>] AssemblyDescription = "EAVT (Entity Attribute Value Time) database for F#"
    let [<Literal>] AssemblyVersion = "0.0.7"
    let [<Literal>] AssemblyFileVersion = "0.0.7"
    let [<Literal>] InternalsVisibleTo = "Fsion.Tests"
